version: 2.1

orbs:
  newman: postman/newman@0.0.2
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      # - run:
      #     command: npm run test
      #     name: Run tests
      - run:
          command: npm run build
          name: Build app

  test: 
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Funfit.postman_collection.json

  deploy: 
    executor: heroku/default 
    steps: 
    - heroku/deploy-via-git: 
        force: true 


workflows: 
  test_my_app:
    jobs: 
      - build
      - test: 
          requires: 
            - build 
      - deploy: 
          requires: 
            - build
            - test
          filters: 
            branches: 
              only: main 
   
